export const backWall = `####
#
# OBJ File Generated by Meshlab
#
####
# Object backWall.obj
#
# Vertices: 4
# Faces: 2
#
####
mtllib ./backWall.obj.mtl

vn 0 0 -1
v -8 0 -8
vn 0 0 -1
v 8 0 -8
vn 0 0 -1
v -8 16 -8
vn 0 0 -1
v 8 16 -8
# 4 vertices, 0 vertices normals


usemtl material_0
f 3//3 1//1 4//4
f 2//2 4//4 1//1
# 2 faces, 0 coords texture

# End of File


`;
