export const ceiling = `####
#
# OBJ File Generated by Meshlab
#
####
# Object ceiling.obj
#
# Vertices: 13
# Faces: 4
#
####
mtllib ./ceiling.obj.mtl

vn 0 -1 0
v -8 16 -8
vn 0 -1 0
v 8 16 -8
vn 0 -1 0
v -8 16 10
vn 0 -1 0
v 8 16 10
# 4 vertices, 0 vertices normals


usemtl material_0
f 2//2 1//1 4//4
f 3//3 4//4 1//1
# 2 faces, 0 coords texture

# End of File
`;
