export const ceilingLight = `####
#
# OBJ File Generated by Meshlab
#
####
# Object ceiling.obj
#
# Vertices: 13
# Faces: 4
#
####
mtllib ./ceiling.obj.mtl

vn 0 1 0
v -3 15.9 3
vn 0 1 0
v 3 15.9 3
vn 0 1 0
v -3 15.9 -3
vn 0 1 0
v 3 15.9 -3
# 4 vertices, 0 vertices normals


usemtl material_0
f 2//2 1//1 4//4
f 3//3 4//4 1//1
# 2 faces, 0 coords texture

# End of File
`;
