export const floor = `####
#
# OBJ File Generated by Meshlab
#
####
# Object floor.obj
#
# Vertices: 4
# Faces: 2
#
####
mtllib ./floor.obj.mtl

vn 0 1 0
v -8 0 -8
vn 0 1 0
v 8 0 -8
vn 0 1 0
v -8 0 10
vn 0 1 0
v 8 0 10
# 4 vertices, 0 vertices normals


usemtl material_0
f 2//2 1//1 4//4
f 3//3 4//4 1//1
# 2 faces, 0 coords texture

# End of File
`;
