export const floor = `####
#
# OBJ File Generated by Meshlab
#
####
# Object floor.obj
#
# Vertices: 4
# Faces: 2
#
####
mtllib ./floor.obj.mtl

vn 0.000000 1.000000 0.000000
v -6.602500 0.024500 -8.880500
vn 0.000000 1.000000 0.000000
v 6.649000 0.024500 -8.880500
vn 0.000000 1.000000 0.000000
v -6.602500 0.024500 10.996900
vn 0.000000 1.000000 0.000000
v 6.649000 0.024500 10.996900
# 4 vertices, 0 vertices normals


usemtl material_0
f 2//2 1//1 4//4
f 3//3 4//4 1//1
# 2 faces, 0 coords texture

# End of File
`;
