export const leftWall = `####
#
# OBJ File Generated by Meshlab
#
####
# Object leftWall.obj
#
# Vertices: 4
# Faces: 2
#
####
mtllib ./leftWall.obj.mtl

vn 1.000000 0.000000 0.000000
v -6.602500 0.024500 -8.880500
vn 1.000000 0.000000 0.000000
v -6.602500 17.146200 -8.880500
vn 1.000000 0.000000 0.000000
v -6.602500 0.024500 10.996900
vn 1.000000 0.000000 0.000000
v -6.602500 17.146200 10.996900
# 4 vertices, 0 vertices normals


usemtl material_0
f 1//1 2//2 3//3
f 4//4 3//3 2//2
# 2 faces, 0 coords texture

# End of File


`;
