export const leftWall = `####
#
# OBJ File Generated by Meshlab
#
####
# Object leftWall.obj
#
# Vertices: 4
# Faces: 2
#
####
mtllib ./leftWall.obj.mtl

vn 1 0 0
v -8 0 -8
vn 1 0 0
v -8 16 -8
vn 1 0 0
v -8 0 10
vn 1 0 0
v -8 16 10
# 4 vertices, 0 vertices normals


usemtl material_0
f 1//1 2//2 3//3
f 4//4 3//3 2//2
# 2 faces, 0 coords texture

# End of File


`;
