export const rightWall = `####
#
# OBJ File Generated by Meshlab
#
####
# Object rightWall.obj
#
# Vertices: 4
# Faces: 2
#
####
mtllib ./rightWall.obj.mtl

vn -0.577350 0.577350 0.577350
v 6.649000 0.024500 -8.880500
vn -0.577350 -0.577350 0.577350
v 6.649000 17.146200 -8.880500
vn -0.707107 0.707107 0.000000
v 6.649000 0.024500 10.996900
vn -0.707107 -0.707107 0.000000
v 6.649000 17.146200 10.996900
# 4 vertices, 0 vertices normals


usemtl material_0
f 2//2 1//1 4//4
f 3//3 4//4 1//1
# 2 faces, 0 coords texture

# End of File

`;
