export const leftWall = `####
#
# OBJ File Generated by Meshlab
#
####
# Object leftWall.obj
#
# Vertices: 4
# Faces: 2
#
####
mtllib ./leftWall.obj.mtl

vn 0.999958 0.008713 0.002820
v -2.982011 -0.158233 -0.243599
vn 0.999916 0.011665 0.005713
v -2.950011 -0.162686 -5.835598
vn 0.999957 0.008783 0.002888
v -3.014011 5.325313 -5.839968
vn 0.999983 0.005831 -0.000005
v -3.014011 5.329765 -0.247969
# 4 vertices, 0 vertices normals


usemtl material_0
f 1//1 3//3 4//4
f 1//1 2//2 3//3
# 2 faces, 0 coords texture

# End of File
`;
