export const rightWall = `####
#
# OBJ File Generated by Meshlab
#
####
# Object rightWall.obj
#
# Vertices: 4
# Faces: 2
#
####
mtllib ./rightWall.obj.mtl

vn -1.000000 0.000000 0.000000
v 2.545989 -0.162686 -5.835598
vn -1.000000 0.000000 0.000000
v 2.545989 -0.158233 -0.243599
vn -1.000000 0.000000 0.000000
v 2.545989 5.329765 -0.247969
vn -1.000000 0.000000 0.000000
v 2.545989 5.325313 -5.839968
# 4 vertices, 0 vertices normals


usemtl material_0
f 2//2 4//4 1//1
f 2//2 3//3 4//4
# 2 faces, 0 coords texture

# End of File
`;
